// ─── Pin-heads index (the fast search tier) ───
// One curated-quality record per pincode (~19.5k rows, ~1.8 MB PLAIN JSON)
// built from the full All-India directory by scripts/build-pin-index.mjs.
//
// Plain JSON on purpose: this tier is what makes nationwide search available
// immediately, so it must not depend on DecompressionStream or streaming-fetch
// support in the host browser/webview. It is a single small response with a
// hard timeout; on failure the caller falls back to curated demo towns.
//
// Records use the same short-key shape as the directory ({p,o,i,s,t,a,n}) so
// normalizeRecord() yields the same GeoPlace pipeline used everywhere.

/** Served from /public — generated by scripts/build-pin-index.mjs. */
export const PIN_INDEX_URL = "/loc/pin-heads.json";

import type { GeoPlace } from "./pincodeData";
import { normalizeRecord } from "./pincodeData";
import { QUICK_LOAD_TIMEOUT_MS, timeoutSignal } from "./gzLoader";

let cachePromise: Promise<GeoPlace[]> | null = null;
let cacheError: Error | null = null;

/**
 * Loads the compact pin index once per session. Fast (single ~1.8 MB JSON
 * response), bounded by a 15s abort timeout. Throws only when this tier
 * fails — callers fall back to curated towns in that case.
 */
export function loadPinIndex(
  sourceUrl: string = PIN_INDEX_URL,
  onProgress?: (pct: number) => void,
): Promise<GeoPlace[]> {
  if (cachePromise) return cachePromise;
  if (cacheError) throw cacheError;

  cachePromise = (async () => {
    let lastErr: unknown = null;
    // One automatic retry for transient network hiccups.
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const res = await fetch(sourceUrl, {
          cache: "force-cache",
          signal: timeoutSignal(QUICK_LOAD_TIMEOUT_MS),
        });
        if (!res.ok) throw new Error(`Location index download failed (HTTP ${res.status})`);
        const raw = (await res.json()) as Record<string, unknown>[];
        onProgress?.(100);
        const out: GeoPlace[] = [];
        for (const rec of raw) {
          const place = normalizeRecord(rec);
          if (!place) continue;
          out.push(place);
        }
        return out;
      } catch (err) {
        lastErr = err;
        if (attempt === 0) {
          // Brief pause before the retry.
          await new Promise((r) => setTimeout(r, 600));
        }
      }
    }
    throw lastErr ?? new Error("Location index could not be loaded.");
  })().catch((err: unknown) => {
    cacheError = err instanceof Error ? err : new Error(String(err));
    cachePromise = null;
    throw cacheError;
  });

  return cachePromise;
}

/** Reset cached index (dev / test helper). */
export function resetPinIndexCache(): void {
  cachePromise = null;
  cacheError = null;
}
