// ─── Pin-heads index (the fast search tier) ───
// One curated-quality record per pincode (~19.5k rows, ~380 KB gz) built from
// the full All-India directory by scripts/build-pin-index.mjs. This small file
// is what makes nationwide search available immediately — the full directory
// only streams in later as background enrichment.
//
// Records use the same short-key shape as the directory ({p,o,i,s,t,a,n}) so
// normalizeRecord() yields the same GeoPlace pipeline used everywhere.

/** Served from /public — generated by scripts/build-pin-index.mjs. */
export const PIN_INDEX_URL = "/loc/pin-heads.json.gz";

import type { GeoPlace } from "./pincodeData";
import { normalizeRecord } from "./pincodeData";

let cachePromise: Promise<GeoPlace[]> | null = null;
let cacheError: Error | null = null;

/**
 * Loads the compact pin index once per session. Fast: ~380 KB compressed,
 * bounded by a 15s abort timeout. Throws only when this tier fails — callers
 * fall back to curated towns in that case.
 */
export function loadPinIndex(
  sourceUrl: string = PIN_INDEX_URL,
  onProgress?: (pct: number) => void,
): Promise<GeoPlace[]> {
  if (cachePromise) return cachePromise;
  if (cacheError) throw cacheError;

  cachePromise = (async () => {
    const { fetchGunzipText, QUICK_LOAD_TIMEOUT_MS } = await import("./gzLoader");
    const text = await fetchGunzipText(sourceUrl, {
      timeoutMs: QUICK_LOAD_TIMEOUT_MS,
      onProgress,
    });
    const raw = JSON.parse(text) as Record<string, unknown>[];
    const out: GeoPlace[] = [];
    for (const rec of raw) {
      const place = normalizeRecord(rec);
      if (!place) continue;
      out.push(place);
    }
    return out;
  })().catch((err: unknown) => {
    cacheError = err instanceof Error ? err : new Error(String(err));
    cachePromise = null;
    throw cacheError;
  });

  return cachePromise;
}

/** Reset cached index (dev / test helper). */
export function resetPinIndexCache(): void {
  cachePromise = null;
  cacheError = null;
}
